# Generated by Django 4.1.5 on 2023-01-20 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watchlist', '0004_alter_review_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='average_rating',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='movie',
            name='total_reviews',
            field=models.IntegerField(default=0),
        ),
    ]
